language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t Anurag11421/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true Anurag11421/react-test npm test

after_success:
  - docker build -t Anurag11421/multi-clint ./client
  - docker build -t Anurag11421/multi-nginx ./nginx
  - docker build -t Anurag11421/multi-server ./server
  - docker build -t Anurag11421/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Docker images to docker hub
  - docker push Anurag11421/multi-clint
  - docker push Anurag11421/multi-nginx
  - docker push Anurag11421/multi-server
  - docker push Anurag11421/multi-worker
